### PR TITLE
Package Refactor and Upgrades

### PR DESCRIPTION
**Pull request by mfixstsci**
Here is the rewrite of `find_tgt_info` and `ephemeris_old2x`. 

To dos:

1. Add plotting function
2. Add MTVT
3. Add GTVT w astroquery
4. Remove old files.

### CODE REVIEW

**Comment by mfixstsci** [comment]
@bholler this is ready for review. I added tests and removed all of the old files. I still need to add the save_figure/save_table functionality to the tool.

**Comment by bholler** [comment]
@mfixstsci Finally had a chance to look at this after the JWST proposal deadline. I'm not able to get the GTVT to run, instead I get this error (I tried this on 2 different computers and got the same errors on each one):

```
Traceback (most recent call last):
  File "/Users/bholler/opt/miniconda3/bin/jwst_gtvt", line 4, in <module>
    __import__('pkg_resources').run_script('jwst-gtvt==0.2.0', 'jwst_gtvt')
  File "/Users/bholler/opt/miniconda3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 662, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/bholler/opt/miniconda3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1459, in run_script
    exec(code, namespace, namespace)
  File "/Users/bholler/opt/miniconda3/lib/python3.9/site-packages/jwst_gtvt-0.2.0-py3.9.egg/EGG-INFO/scripts/jwst_gtvt", line 35, in <module>
    main(args)
  File "/Users/bholler/opt/miniconda3/lib/python3.9/site-packages/jwst_gtvt-0.2.0-py3.9.egg/EGG-INFO/scripts/jwst_gtvt", line 28, in main
    eph.get_fixed_target_positions(ra, dec)
NameError: name 'ra' is not defined
```

I am able to get the MTVT to run (and I really like the output plot!), but I get this at the end of the table output in my terminal: 

```
/Users/bholler/opt/miniconda3/lib/python3.9/site-packages/jwst_gtvt-0.2.0-py3.9.egg/jwst_gtvt/plotting.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['times'] = Time(df['MJD'], format='mjd').datetime
```

I also noticed that "jwst_mtvt 2" gives Pallas and "jwst_mtvt 5" gives Astraea, both without the --smallbody flag. I would have expected Venus and Jupiter. Is the --smallbody understood now, i.e., small bodies are the default? That's fine, but the major bodies can't be specified just by their names; typing "jwst_mtvt Jupiter" gives an error.

On one computer I had to manually install the pandas and tabulate modules. On the other I had to manually install tabulate.

**Comment by mfixstsci** [comment]
> @mfixstsci Finally had a chance to look at this after the JWST proposal deadline. I'm not able to get the GTVT to run, instead I get this error (I tried this on 2 different computers and got the same errors on each one):
> 
> ```
> Traceback (most recent call last):
>   File "/Users/bholler/opt/miniconda3/bin/jwst_gtvt", line 4, in <module>
>     __import__('pkg_resources').run_script('jwst-gtvt==0.2.0', 'jwst_gtvt')
>   File "/Users/bholler/opt/miniconda3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 662, in run_script
>     self.require(requires)[0].run_script(script_name, ns)
>   File "/Users/bholler/opt/miniconda3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1459, in run_script
>     exec(code, namespace, namespace)
>   File "/Users/bholler/opt/miniconda3/lib/python3.9/site-packages/jwst_gtvt-0.2.0-py3.9.egg/EGG-INFO/scripts/jwst_gtvt", line 35, in <module>
>     main(args)
>   File "/Users/bholler/opt/miniconda3/lib/python3.9/site-packages/jwst_gtvt-0.2.0-py3.9.egg/EGG-INFO/scripts/jwst_gtvt", line 28, in main
>     eph.get_fixed_target_positions(ra, dec)
> NameError: name 'ra' is not defined
> ```
> 
> I am able to get the MTVT to run (and I really like the output plot!), but I get this at the end of the table output in my terminal:
> 
> ```
> /Users/bholler/opt/miniconda3/lib/python3.9/site-packages/jwst_gtvt-0.2.0-py3.9.egg/jwst_gtvt/plotting.py:12: SettingWithCopyWarning: 
> A value is trying to be set on a copy of a slice from a DataFrame.
> Try using .loc[row_indexer,col_indexer] = value instead
> 
> See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
>   df['times'] = Time(df['MJD'], format='mjd').datetime
> ```
> 
> I also noticed that "jwst_mtvt 2" gives Pallas and "jwst_mtvt 5" gives Astraea, both without the --smallbody flag. I would have expected Venus and Jupiter. Is the --smallbody understood now, i.e., small bodies are the default? That's fine, but the major bodies can't be specified just by their names; typing "jwst_mtvt Jupiter" gives an error.
> 
> On one computer I had to manually install the pandas and tabulate modules. On the other I had to manually install tabulate.

Hey @bholler thank you for responding to this. I believe there is a problem with the conversion for RA and Dec that I implemented. I am going to look into that now. As for the small body problem the flag might be reversed. I will have to double check!

**Comment by mfixstsci** [comment]
Okay, I found the bugs, less serious than I thought. Feel free to pull and try it out again.

**Comment by bholler** [comment]
I see the following resolved issues:
-I did not need to install other packages after running the setup.py.
-The jwst_gtvt works!
-The --smallbody flag now works as expected.

The pandas warning after the output table is still present.

One new issue: Typing "jwst_mtvt 2" results in an error, presumably because Venus is never in the JWST FOR. Mars (4) and Jupiter (5) work. I am not opposed to the MTVT not running for targets that cannot be observed by JWST, but instead of python errors it might be better to provide our own error message that explains the lack of results. Perhaps something like: "Target Visibility Error: The target you have selected is not in the JWST field of regard (FOR) during the specified date range. Please specify a different target or a different date range."

**Comment by mfixstsci** [comment]
@bholler great thank you for testing. @PatrickOgle we have these changes ready to merge. Let me know if you have any questions. @nespinoza once we get approval, we can start integrating the new GTVT into exoctk and exomast 👍

**Comment by melanieclarke** [comment]
@mfixstsci - I'm watching this PR because I'd like to use the new functionality in a NIRSpec visualization tool.  Would it be possible to loosen up the install_requires versions to make this package more usable in combination with other projects? Using '>=' instead of '==' would help a lot.

**Comment by mfixstsci** [comment]
@melanieclarke I can do that. I have a bad habit of pinning versions with `==`. I will go ahead and fix that this afternoon!

**Comment by mfixstsci** [comment]
@bholler and I met with with @PatrickOgle on Wednesday. Code review was done and all changes have been approved, waiting on some notes for aesthetic and small changes to plots and the repo. Once those are done, I will be merging next week @melanieclarke

**Comment by melanieclarke** [comment]
> Once those are done, I will be merging next week @melanieclarke

Excellent, thanks!

**Comment by mfixstsci** [comment]
@bholler -- Would you by chance be able to send me the notes from the meeting? This way I can make the changes requested by Patrick and start integrating changes with our dependencies. Thank you!

**Comment by bholler** [comment]
Comments from the G/MTVT code review meeting on 5/24:

- **Trim decimal places in the title.** For fixed targets specified in sexagesimal format, and without the flag for a user-specified name, the title includes way too many decimal places when converting to degree format. Trimming down to 3-5 decimal places would be ideal.
- **Reword the y-axis labels for clarity.** Patrick asked if the position angles reported for the various instruments were aperture or V3. The current y-axis label appears to be "Available Position Angles (Degrees)" in the development branch. I would suggest (1) replacing "Degrees" with the symbol to save space and (2) adding "Aperture" to the label. Unfortunately, that probably means the y-axis label for the V3PA plot needs to be handled separately; keeping the current label for the V3PA plot would be appropriate.
- **Update default dates.** To support both Cycle 2 and Cycle 3, I would recommend updating the default dates to July 1, 2023, to the latest available date for the JWST ephemeris. Looking at Horizons, the latest date appears to be May 29, 2025. This is 1 month short of the full Cycle 3 period. This is a possible excuse for waiting a few more weeks to perform the release, in the hopes that the end date gets pushed to June 30, 2025 (or beyond) by waiting another month.
- **Improve the error message for a bad date.** Mees and I had a discussion about this on Slack. This message should be different from observing a target that can never be observed by JWST (e.g., Venus). If I remember correctly, during the code review this error case provided a python error message, which makes the code look broken.
- **Make the tool robust to Horizons being down.** The case of someone working with the tool on an airplane, or somewhere else without wifi, is now accounted for by shifting to use a default JWST ephemeris packaged with the tool, but the same pathway should be available if Horizons is down. While this doesn't happen often, there are occasions where Horizons is updated and is unavailable, or a connection could time out, etc. In these cases, the tool should default to the stored ephemeris as well.

**Comment by bholler** [comment]
To follow up after a discussion with Mees, the G/MTVT should be released ASAP to support other tools that use it as a dependency. At a later time (presumably >July 1) we can perform a patch release to update the fallback JWST ephemeris and the default dates to support all of Cycle 3 (to June 30, 2025). I believe the JWST ephemeris goes out to 2 years past when the latest delivery is made, so a delivery in July would cover the full Cycle 3 period.

**Comment by bholler** [comment]
After a lot of time and rewrites (thanks @mfixstsci!), **I believe the G/MTVT is ready to be released**. All readme text issues have been addressed and the tools work as expected.

Very, very, very minor comments for the next version (making notes here for posterity):
- The "Ecliptic Latitude" quantity in the print-out should also have sig figs truncated to 4 decimal places.
- After running the "delete_cache" command, the print-out has 2 periods at the end of the sentence ("Cache deleted..").

**Review by bholler — APPROVED** [review]
Let's get this merged!

**Pull request merged**
