### PR TITLE
INS Community Software Tier Two Standards Pt. 2

### PR DESCRIPTION
**Pull request by mfixstsci**
Adding more requirements to the repository outlined here:
https://github.com/spacetelescope/ins-jwst-community-software/#contents

### CODE REVIEW

**Comment by mfixstsci** [comment]
- ~~Software Repository Must Have a Code of Conduct File~~
- Project Must Document Citation Information
- Software Must Enforce Language-specific Coding Standards (e.g. PEP8)
- ~~Software Must Support Recent Version(s) of Python~~
- ~~Project Must Have or Reference a Documented git Workflow or Contributor's Guide~~
- Software Must Document Modules, Classes, and Functions
- ~~Project Have Some Unit and/or Regression Tests~~
- Project Must Document a Release Procedure
- Project Must Provide Release Notes
- ~~Project Must Have Backup Maintainers~~
- ~~Project Must Utilize Code Review/Approval for New Changes~~
- ~~Project Must Use an Automated Dependency Update Tool~~

**Comment by mfixstsci** [comment]
@bholler I was hoping we could make some citation information for the tier II software standards. I want to make sure to include everybody and not let anything fall through the cracks:

https://github.com/spacetelescope/ins-jwst-community-software/blob/master/tier2_standards/citation_information.md

I can make a first pass unless you would like to do it. Thanks!

**Comment by bholler** [comment]
@mfixstsci Given that this tool does not have any publications associated with it, I would recommend the following citation:

_If you use the JWST General Target Visibility Tool (GTVT) or JWST Moving Target Visibility Tool (MTVT) for work/research presented in a publication, or as a dependency in a software package, we recommend and encourage the following acknowledgment:_

_This work made use of the JWST General Target Visibility Tool (GTVT) and/or the JWST Moving Target Visibility Tool (MTVT) originally written by Matthew Hill, expanded for moving targets by Michael Kelley, and maintained by Mees Fix._

**Comment by mfixstsci** [comment]
@bourque @shanosborne I wanted to ask you for advice/mention something about the source code here. I have most of the tier II standards crossed off, but I am worried about accomplishing the PEP8 and Docstring requirement. The source code is in a pretty rough state and I don't have a lot of time to work on updating/documenting all of it (that's if I understand what it's doing in the first place). This ties into the PEP8 requirement, there needs to be some major overhauling done, should I go ahead and try to just do what I can and the finish the rest later? Thanks!

**Comment by mfixstsci** [comment]
> @mfixstsci Given that this tool does not have any publications associated with it, I would recommend the following citation:
> 
> _If you use the JWST General Target Visibility Tool (GTVT) or JWST Moving Target Visibility Tool (MTVT) for work/research presented in a publication, or as a dependency in a software package, we recommend and encourage the following acknowledgment:_
> 
> _This work made use of the JWST General Target Visibility Tool (GTVT) and/or the JWST Moving Target Visibility Tool (MTVT) originally written by Matthew Hill, expanded for moving targets by Michael Kelley, and maintained by Mees Fix._

Thanks @bholler

**Comment by bourque** [comment]
> @bourque @shanosborne I wanted to ask you for advice/mention something about the source code here. I have most of the tier II standards crossed off, but I am worried about accomplishing the PEP8 and Docstring requirement. The source code is in a pretty rough state and I don't have a lot of time to work on updating/documenting all of it (that's if I understand what it's doing in the first place). This ties into the PEP8 requirement, there needs to be some major overhauling done, should I go ahead and try to just do what I can and the finish the rest later? Thanks!

@mfixstsci Thanks for letting @shanosborne and I know.  We will make a note that the PEP8 and API doc standards will be a substantial effort and make sure to communicate that to the mission office so that they know that these two standards may take a while.  Aside from that, I would suggest to try to get the rest of the standards done first, and then we can circle back to these two.

**Review by mfixstsci — COMMENTED** [review]
Ready to merge.

**Pull request merged**
