### PR TITLE
Add pysiaf

### PR DESCRIPTION
**Pull request by mfixstsci**

### CODE REVIEW

**Comment by mfixstsci** [comment]
I am still looking into that. I didn't see it when I was looking through the SIAF file.

**Comment by mfixstsci** [comment]
@skendrew 

Here are all of the available methods/attributes for the `NIRCAM SIAF` and I don't see the angle they are asking for. It would very well be a type but I don't know enough about the source code to make that call

```
In [27]: import pysiaf                                                                                                                                     

In [28]: siaf = pysiaf.Siaf('NIRCAM')                                                                                                                      
^[[A
In [29]: dir(siaf['NRCALL_FULL'])                                                                                                                          
Out[29]: 
['AperName',
 'AperShape',
 'AperType',
 'Comment',
 'DDCName',
 'DetSciParity',
 'DetSciYAngle',
 'Idl2SciX00',
 'Idl2SciX10',
 'Idl2SciX11',
 'Idl2SciX20',
 'Idl2SciX21',
 'Idl2SciX22',
 'Idl2SciX30',
 'Idl2SciX31',
 'Idl2SciX32',
 'Idl2SciX33',
 'Idl2SciX40',
 'Idl2SciX41',
 'Idl2SciX42',
 'Idl2SciX43',
 'Idl2SciX44',
 'Idl2SciX50',
 'Idl2SciX51',
 'Idl2SciX52',
 'Idl2SciX53',
 'Idl2SciX54',
 'Idl2SciX55',
 'Idl2SciY00',
 'Idl2SciY10',
 'Idl2SciY11',
 'Idl2SciY20',
 'Idl2SciY21',
 'Idl2SciY22',
 'Idl2SciY30',
 'Idl2SciY31',
 'Idl2SciY32',
 'Idl2SciY33',
 'Idl2SciY40',
 'Idl2SciY41',
 'Idl2SciY42',
 'Idl2SciY43',
 'Idl2SciY44',
 'Idl2SciY50',
 'Idl2SciY51',
 'Idl2SciY52',
 'Idl2SciY53',
 'Idl2SciY54',
 'Idl2SciY55',
 'InstrName',
 'Sci2IdlDeg',
 'Sci2IdlX00',
 'Sci2IdlX10',
 'Sci2IdlX11',
 'Sci2IdlX20',
 'Sci2IdlX21',
 'Sci2IdlX22',
 'Sci2IdlX30',
 'Sci2IdlX31',
 'Sci2IdlX32',
 'Sci2IdlX33',
 'Sci2IdlX40',
 'Sci2IdlX41',
 'Sci2IdlX42',
 'Sci2IdlX43',
 'Sci2IdlX44',
 'Sci2IdlX50',
 'Sci2IdlX51',
 'Sci2IdlX52',
 'Sci2IdlX53',
 'Sci2IdlX54',
 'Sci2IdlX55',
 'Sci2IdlY00',
 'Sci2IdlY10',
 'Sci2IdlY11',
 'Sci2IdlY20',
 'Sci2IdlY21',
 'Sci2IdlY22',
 'Sci2IdlY30',
 'Sci2IdlY31',
 'Sci2IdlY32',
 'Sci2IdlY33',
 'Sci2IdlY40',
 'Sci2IdlY41',
 'Sci2IdlY42',
 'Sci2IdlY43',
 'Sci2IdlY44',
 'Sci2IdlY50',
 'Sci2IdlY51',
 'Sci2IdlY52',
 'Sci2IdlY53',
 'Sci2IdlY54',
 'Sci2IdlY55',
 'UseAfterDate',
 'V2Ref',
 'V3IdlYAngle',
 'V3Ref',
 'V3SciXAngle',
 'V3SciYAngle',
 'VIdlParity',
 'XDetRef',
 'XDetSize',
 'XIdlVert1',
 'XIdlVert2',
 'XIdlVert3',
 'XIdlVert4',
 'XSciRef',
 'XSciScale',
 'XSciSize',
 'YDetRef',
 'YDetSize',
 'YIdlVert1',
 'YIdlVert2',
 'YIdlVert3',
 'YIdlVert4',
 'YSciRef',
 'YSciScale',
 'YSciSize',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_accepted_aperture_types',
 '_correct_dva',
 '_dva_parameters',
 '_initial_attributes_validated',
 '_observatory',
 '_parent_apertures',
 'closed_polygon_points',
 'complement',
 'convert',
 'corners',
 'correct_for_dva',
 'det_to_idl',
 'det_to_raw',
 'det_to_sci',
 'det_to_tel',
 'detector_transform',
 'distortion_transform',
 'get_polynomial_coefficients',
 'idl_to_det',
 'idl_to_raw',
 'idl_to_sci',
 'idl_to_tel',
 'observatory',
 'path',
 'plot',
 'plot_detector_channels',
 'plot_frame_origin',
 'raw_to_det',
 'raw_to_idl',
 'raw_to_sci',
 'raw_to_tel',
 'reference_point',
 'sci_to_det',
 'sci_to_idl',
 'sci_to_raw',
 'sci_to_tel',
 'set_polynomial_coefficients',
 'tel_to_det',
 'tel_to_idl',
 'tel_to_raw',
 'tel_to_sci',
 'telescope_transform',
 'validate',
 'verify']
```

**Comment by mfixstsci** [comment]
> NIRCam consulted with the TEL branch and we agree that the mention of "V2IdlYAng" is just a typo and should be "V3IdlYAng" as for all other instruments. There is no special treatment of NIRCam angles in the SIAF. From Matthew Lallo's email to me:
> 
> > I don’t see any problem anywhere. The pasted screen snap looks as expected regarding PA-V3 and the NIRCam mosaics and offsets execute as expected  for us on the OTB.
> > We’re not aware of any special treatment for NIRCam regarding these conventions or definitions.
> 
> Also, given that there are minor discrepancies observed, I commented via email:
> 
> > It would be important that you double check that the PA ranges between the GTVT and what displayed in APT are the same, once you start using the up-to-date version of the SIAF, just as a sanity check.

@bholler @JAStansberry 

@mgennaro I am responding to a comment in #24 I went ahead and made the changes in the code base. We are trying to release a new version of the software and would like to include this as well. I am concerned about some of the values we are changing:

```
 NRCALL_FULL_V2IdlYang = -0.0265
 NRS_FULL_MSA_V3IdlYang = 137.4874
 NIS_V3IdlYang = -0.57
 MIRIM_FULL_V3IdlYang = 5.0152
 FGS1_FULL_V3IdlYang = -1.2508
```

I am using the most up-to-date version of `pysiaf` on pip `PRDOPSSOC-034` and here are the values from the `siaf`:

```
NRCALL_FULL_V3IdlYang = get_angle('NIRCAM', 'NRCALL_FULL', 'V3IdlYAngle') = -0.11255124
NRS_FULL_MSA_V3IdlYang = get_angle('NIRSPEC', 'NRS_FULL_MSA', 'V3IdlYAngle') = 138.49234009
NIS_V3IdlYang = get_angle('NIRISS', 'NIS_CEN', 'V3IdlYAngle') = 0.56987018
MIRIM_FULL_V3IdlYang = get_angle('MIRI', 'MIRIM_FULL', 'V3IdlYAngle') = 4.83425324
FGS1_FULL_V3IdlYang = get_angle('FGS', 'FGS1_FULL', 'V3IdlYAngle') = -1.25081713
```

The angle I am most concerned about is the `NRCALL_FULL_V3IdlYang`. It's an order of magnitude larger than the value we currently have hard coded.

**Comment by mgennaro** [comment]
Hi @mfixstsci , I can confirm that (besides the V2->V3 typo that needs fixing) the value you should be using for NRCALL_FULL_V3IdlYang is -0.11255124.
I found trace of the old value of -0.0265 in the NIRCAM_SIAF file under the PRD version named PRDOPSSOC-G-011, which in turn can be found under PRD_data in the pysiaf distribution. That PRD predates my presence in JWST thus I am not sure where those value came from, but yes, the "1 order of magnitude" change happened at some point in the past, and it is expected

**Comment by mfixstsci** [comment]
> Hi @mfixstsci , I can confirm that (besides the V2->V3 typo that needs fixing) the value you should be using for NRCALL_FULL_V3IdlYang is -0.11255124.
> I found trace of the old value of -0.0265 in the NIRCAM_SIAF file under the PRD version named PRDOPSSOC-G-011, which in turn can be found under PRD_data in the pysiaf distribution. That PRD predates my presence in JWST thus I am not sure where the value came from, but yes, the "1 order of magnitude" change happened at some point in the past, and it is expected

@mgennaro Thank you for verifying! @bholler want to pull this PR down and test it? All of the tests in the branch are currently passing so I don't foresee you having any issues.

@JAStansberry What do you think of this? I think in the long run, getting the most up-to-date values from the `siaf` will be useful when commissioning activities begin and the `siaf` is getting updated quite a bit. I know from a user stand point, the angle changing slightly might now make a very big difference, but from a development standpoint, I think this is probably for the best moving forward.

**Review by bholler — APPROVED** [review]
@mfixstsci I compared the current version of the G/MTVT to the `add-pysiaf` branch and the new PA values check out. Even though the NIRCam value changed by an order of magnitude, it results in a change in PA of only about 0.1 degree for fixed and moving targets. MIRI, NIRSpec, and NIRISS all show changes in PA of about 1 degree, probably due to their positions in the focal plane compared to NIRCam. That being said, a 1 degree change in PA is unnoticeable, especially since the purpose of this tool is to get a quick look at target visibility. The updated JWST ephemeris is going to change things way more than this.

**Comment by JAStansberry** [comment]
I like it - this is a more robust solution and there will be more changes in SIAF after launch. As Bryan says, the V3 angle doesn't change much due to this particular update, others may use the code for other things (i.e. new code), and the details in SIAF could matter significantly for those applications.


John Stansberry
Space Telescope Science Institute
JWST -- NIRCam Commissioning and Solar System Lead
        NIRCam Operations
410  338  2442


________________________________

**Comment by mfixstsci** [comment]
Just merged in #60 and tested the tool and it works just as expected. All of the checks are passing and with @JAStansberry and @bholler approval, I am going to merge.

**Pull request merged**
