### PR TITLE
Updates to README.md

### PR DESCRIPTION
**Pull request by mfixstsci**
Updating figures and commands.

### CODE REVIEW

**Comment by mfixstsci** [comment]
@bholler easy PR just to update the `README.md` with our new changes before preparing the `0.2.0` release.

**Comment by mfixstsci** [comment]
@JAStansberry and @bholler we might need to update the `jdox` page now too.

**Review by bholler — CHANGES_REQUESTED** [review]
Since there was no need to update the ephemeris, the earliest available date has not changed. That should still be 2020-01-01 in the help blurb. The updated example is fine though.

**Comment by bholler** [comment]
And I will look into updating the JDOX pages.

**Comment by mfixstsci** [comment]
@bholler I set the default date for the tool to be `2022-06-01` so if you enter anything earlier, it will fail. I can change the earliest allowed date back to 01-01-2020. I figured we would want the defaults to be projected to next summer for the next JWST cycle, correct?

**Comment by bholler** [comment]
@mfixstsci Ah, I figured those would be 2 separate things: the default and the earliest available. But if they are the same thing then I would actually suggest the new default be 2021-11-01 so that we can use the tool on potential commissioning targets. The new example you ran for the readme is still valid, so no need to change that.

**Comment by JAStansberry** [comment]
Ah - yep, that's an important distinction. We don't want to disable it for planning of commissioning activities!  Good catch!


John Stansberry
Space Telescope Science Institute
JWST -- NIRCam Commissioning and Solar System Lead
        NIRCam Operations
410  338  2442


________________________________

**Comment by mfixstsci** [comment]
Okay, this PR seems less important since we are going to be reverting the changes. I am going to close it, open another PR and fix the default dates.

**Pull request closed without merging**
